# Generated by Django 3.0.1 on 2019-12-22 19:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('sha', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('commit_order', models.PositiveIntegerField()),
                ('author', django.contrib.postgres.fields.jsonb.JSONField()),
                ('committer', django.contrib.postgres.fields.jsonb.JSONField()),
                ('committer_name', models.CharField(max_length=100)),
                ('committer_date', models.DateTimeField()),
                ('commit_message', models.TextField()),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField()),
                ('comment_count', models.IntegerField()),
                ('parents', django.contrib.postgres.fields.jsonb.JSONField()),
                ('additions', models.IntegerField()),
                ('deletions', models.IntegerField()),
                ('files', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fail_rate_overall', models.FloatField(blank=True, null=True)),
                ('data_sync', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Committer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('fail_rate_overall', models.FloatField(blank=True, null=True)),
                ('fail_rate_recently', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('build_id', models.CharField(max_length=20)),
                ('build_order', models.IntegerField()),
                ('build_result', models.CharField(max_length=20)),
                ('commit_num', models.PositiveIntegerField(default=0)),
                ('fail_rate_recently', models.FloatField(blank=True, null=True)),
                ('commits', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
            ],
            options={
                'unique_together': {('project_name', 'build_id')},
            },
        ),
    ]
