# Generated by Django 3.0.1 on 2019-12-22 19:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_mining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='committer',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='files',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='parents',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
