# Generated by Django 3.0.1 on 2019-12-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_mining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='file_ids',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
