# Generated by Django 3.0.1 on 2019-12-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_mining', '0002_commit_file_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='file_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha',
            field=models.CharField(max_length=100),
        ),
    ]
