# Generated by Django 3.0.1 on 2019-12-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_mining', '0008_build_commit_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='fail_rate_recently',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
