# Generated by Django 3.0.1 on 2019-12-22 06:00

from django.db import migrations, models
from software_mining.models import Build, Commit


def fix_project_name(apps, schema_editor):
    builds = Build.objects.all()
    print('fix commit project name')
    for b in builds:
        b.commits.update(project_name=b.project_name)
    print('fix file project name')
    commits = Commit.objects.all()
    for c in commits:
        c.files.update(project_name=c.project_name)


class Migration(migrations.Migration):

    dependencies = [
        ('software_mining', '0004_auto_20191221_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),

        migrations.RunPython(fix_project_name, hints={'target_db': 'default'}),
    ]
