# Generated by Django 3.0.1 on 2019-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_mining', '0005_auto_20191222_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('fail_rate_overall', models.FloatField(blank=True, null=True)),
                ('fail_rate_recently', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commit',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fail_rate_overall', models.FloatField(blank=True, null=True)),
                ('fail_rate_recently', models.FloatField(blank=True, null=True)),
                ('all_committer', models.ManyToManyField(to='software_mining.Committer')),
            ],
        ),
    ]
