# Generated by Django 3.0.1 on 2019-12-22 09:15

from django.db import migrations, models

from software_mining.models import Project, Build


def add_projects(apps, schema_editor):
    data = Build.objects.values('project_name').annotate(c=models.Count('build_id'))
    for item in data:
        Project.objects.get_or_create(
            name=item['project_name']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('software_mining', '0006_auto_20191222_0908'),
    ]

    operations = [
        migrations.RunPython(add_projects, hints={'target_db': 'default'}),
    ]
