# Generated by Django 3.0.1 on 2019-12-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_mining', '0007_auto_20191222_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='commit_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
